title: <p align="center"> Shaik Imthiyaz Ahamed </p>
logo: /assets/img/Imthiyaz.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/imthiyazahamedsk/">LinkedIn</a> |
  <a href="https://github.com/imthiyazahamed01">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.

  <br>
  </p>
  #<a href="pdf/resume.pdf">Resume</a> |
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
#google_analytics:
#  Also handing the Big Data from real-time Ad call data.
#  Worked with IBM Research at Big Data Analytics team.
#  Working in AdTech domain for 3 years.


theme: jekyll-theme-minimal
